language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'

before_script:
  - composer install

script: phpunit --coverage-clover clover.xml

after_success: vendor/bin/php-coveralls  -v --exclude-no-stmt -x clover.xml

notifications:
  email:
    - mfkgdyve456@126.com
